### ISSUE TITLE
Correções - Documento de metodologias

### ISSUE THREAD

**Issue by eliseukadesh67** [Interacao-Humano-Computador/2021.2-Prefeitura-Verdelandia#8]
### Descrição:

Como ja descrito na issue #6, apos o feedback da entrega 1, alguns pontos de melhora foram levantados a respeito do documento de metodologias.

### Critérios de aceitação:

- [x] Coerencia na documentação;
- [x] Possuir referências e citações corretas (se houver);
- [x] Possuir embasamento teórico (se precisar);
- [x] Respeitar a padronização dos documentos;
- [x] Possuir versionamento correto;
- [ ] Evidenciar pelo menos um revisor por documento;  

### Tarefas:

- [ ] Numerar o titulo da comunicação;
- [x] Adicionar justify ao documento;
- [ ] Atualizar a questão das dailys e reuniões que não serao mais diárias;

### Issue(s) relacionada(s)
- #7

**Comment by AntonioIgorCarvalho** [comment]
Pull request aberto para justificar os textos
